#!/bin/sh

INKBOX_KERNEL="/boot/zImage-inkbox"
NICKEL_KERNEL="/nickel-onboard/zImage-nickel"
CPR_RL=0.1
CPR_YR="2021-2025"

mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run

uname -a; echo "Quill OS Linux SPL kernel release ${CPR_RL} - Copyright (C) ${CPR_YR} Nicolas Mailloux"

/usr/local/bin/auto-boot.sh
if [ ${?} != 0 ]; then
	mkdir -p /boot
	mount -t ext4 /dev/mmcblk0p1 /boot
	kexec -l /boot/zImage
	sync
	umount -l -f /boot
	sync
	kexec -e
fi
